version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - $PWD/volumes/influxdb/data:/var/lib/influxdb2
      - $PWD/volumes/influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=MaxiAdmin
      - DOCKER_INFLUXDB_INIT_ORG=IoT
      - DOCKER_INFLUXDB_INIT_BUCKET=projet

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    links:
      - influxdb
    volumes:
      - $PWD/projet.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/geeks-r-us/mqtt-panel/releases/download/v1.0.7/geeksrus-mqtt-panel-1.0.7.zip;mqtt-panel
    volumes:
      - $PWD/volumes/grafana:/var/lib/grafana
      - $PWD/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - influxdb


#influx delete --bucket projet --start '1970-01-01T00:00:00Z' --stop '2023-04-26T11:34:00Z'